//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOS.EasyBuyCycles.Shared.Properties
{


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class DescriptionResource
	{

		private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string COUNTRY {
        get {
        return ResourceManager.GetString("COUNTRY", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string POSTALCODE {
        get {
        return ResourceManager.GetString("POSTALCODE", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Address 3.
        /// </summary>
        public static string ADDRESS3 {
        get {
        return ResourceManager.GetString("ADDRESS3", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string ADDRESS2 {
        get {
        return ResourceManager.GetString("ADDRESS2", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string ADDRESS1 {
        get {
        return ResourceManager.GetString("ADDRESS1", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Image Path.
        /// </summary>
        public static string IMAGEPATH {
        get {
        return ResourceManager.GetString("IMAGEPATH", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string DISCONTINUED {
        get {
        return ResourceManager.GetString("DISCONTINUED", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Minimum Reorder Quantity.
        /// </summary>
        public static string MINIMUMREORDERQUANTITY {
        get {
        return ResourceManager.GetString("MINIMUMREORDERQUANTITY", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Target Level.
        /// </summary>
        public static string TARGETLEVEL {
        get {
        return ResourceManager.GetString("TARGETLEVEL", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        public static string REORDERLEVEL {
        get {
        return ResourceManager.GetString("REORDERLEVEL", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to List Price.
        /// </summary>
        public static string LISTPRICE {
        get {
        return ResourceManager.GetString("LISTPRICE", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Standard Cost.
        /// </summary>
        public static string STANDARDCOST {
        get {
        return ResourceManager.GetString("STANDARDCOST", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CATEGORY {
        get {
        return ResourceManager.GetString("CATEGORY", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCRIPTION {
        get {
        return ResourceManager.GetString("DESCRIPTION", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CODE {
        get {
        return ResourceManager.GetString("CODE", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Discount Percent.
        /// </summary>
        public static string DISCOUNTPERCENT {
        get {
        return ResourceManager.GetString("DISCOUNTPERCENT", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UNITPRICE {
        get {
        return ResourceManager.GetString("UNITPRICE", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string QUANTITY {
        get {
        return ResourceManager.GetString("QUANTITY", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Product Internal ID.
        /// </summary>
        public static string PRODUCTINTERNALID {
        get {
        return ResourceManager.GetString("PRODUCTINTERNALID", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Order Internal ID.
        /// </summary>
        public static string ORDERINTERNALID {
        get {
        return ResourceManager.GetString("ORDERINTERNALID", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Internal ID.
        /// </summary>
        public static string INTERNALID11 {
        get {
        return ResourceManager.GetString("INTERNALID11", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Sales Person Name.
        /// </summary>
        public static string SALESPERSONNAME {
        get {
        return ResourceManager.GetString("SALESPERSONNAME", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Sales Person Internal ID.
        /// </summary>
        public static string SALESPERSONINTERNALID {
        get {
        return ResourceManager.GetString("SALESPERSONINTERNALID", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
        get {
        return ResourceManager.GetString("STATUS", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Order Memo.
        /// </summary>
        public static string ORDERMEMO {
        get {
        return ResourceManager.GetString("ORDERMEMO", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Shipping Address Internal ID.
        /// </summary>
        public static string SHIPPINGADDRESSINTERNALID {
        get {
        return ResourceManager.GetString("SHIPPINGADDRESSINTERNALID", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Delivery Memo.
        /// </summary>
        public static string DELIVERYMEMO {
        get {
        return ResourceManager.GetString("DELIVERYMEMO", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Warehouse Name.
        /// </summary>
        public static string WAREHOUSENAME {
        get {
        return ResourceManager.GetString("WAREHOUSENAME", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Warehouse Internal ID.
        /// </summary>
        public static string WAREHOUSEINTERNALID {
        get {
        return ResourceManager.GetString("WAREHOUSEINTERNALID", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Purchase Order Number.
        /// </summary>
        public static string PURCHASEORDERNUMBER {
        get {
        return ResourceManager.GetString("PURCHASEORDERNUMBER", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Order Date Time.
        /// </summary>
        public static string ORDERDATETIME {
        get {
        return ResourceManager.GetString("ORDERDATETIME", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Customer Internal ID.
        /// </summary>
        public static string CUSTOMERINTERNALID {
        get {
        return ResourceManager.GetString("CUSTOMERINTERNALID", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Audit Stamps.
        /// </summary>
        public static string AUDITSTAMPTABTEXT {
        get {
        return ResourceManager.GetString("AUDITSTAMPTABTEXT", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string TRUEFLAG {
        get {
        return ResourceManager.GetString("TRUEFLAG", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string FALSEFLAG {
        get {
        return ResourceManager.GetString("FALSEFLAG", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to EasyBuyCycles Logon.
        /// </summary>
        public static string LOGONTITLETEXT {
        get {
        return ResourceManager.GetString("LOGONTITLETEXT", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to EasyBuyCycles.
        /// </summary>
        public static string LOGONSYSTEMNAME {
        get {
        return ResourceManager.GetString("LOGONSYSTEMNAME", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string DETAILTABTEXT {
        get {
        return ResourceManager.GetString("DETAILTABTEXT", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string BASIC {
        get {
        return ResourceManager.GetString("BASIC", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Extended.
        /// </summary>
        public static string EXTENDED {
        get {
        return ResourceManager.GetString("EXTENDED", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Internal ID.
        /// </summary>
        public static string INTERNALID1 {
        get {
        return ResourceManager.GetString("INTERNALID1", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Last Modified With.
        /// </summary>
        public static string LASTMODIFIEDWITH {
        get {
        return ResourceManager.GetString("LASTMODIFIEDWITH", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Last Modified By.
        /// </summary>
        public static string LASTMODIFIEDBY {
        get {
        return ResourceManager.GetString("LASTMODIFIEDBY", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Last Modified At.
        /// </summary>
        public static string LASTMODIFIEDAT {
        get {
        return ResourceManager.GetString("LASTMODIFIEDAT", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Created With.
        /// </summary>
        public static string CREATEDWITH {
        get {
        return ResourceManager.GetString("CREATEDWITH", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CREATEDBY {
        get {
        return ResourceManager.GetString("CREATEDBY", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        public static string CREATEDAT {
        get {
        return ResourceManager.GetString("CREATEDAT", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Purchase Points.
        /// </summary>
        public static string PURCHASEPOINTS {
        get {
        return ResourceManager.GetString("PURCHASEPOINTS", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        public static string MEMO {
        get {
        return ResourceManager.GetString("MEMO", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL {
        get {
        return ResourceManager.GetString("EMAIL", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string TELEPHONE {
        get {
        return ResourceManager.GetString("TELEPHONE", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Billing Country.
        /// </summary>
        public static string BILLINGCOUNTRY {
        get {
        return ResourceManager.GetString("BILLINGCOUNTRY", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Billing Postal Code.
        /// </summary>
        public static string BILLINGPOSTALCODE {
        get {
        return ResourceManager.GetString("BILLINGPOSTALCODE", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Billing Address 3.
        /// </summary>
        public static string BILLINGADDRESS3 {
        get {
        return ResourceManager.GetString("BILLINGADDRESS3", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Billing Address 2.
        /// </summary>
        public static string BILLINGADDRESS2 {
        get {
        return ResourceManager.GetString("BILLINGADDRESS2", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Billing Address 1.
        /// </summary>
        public static string BILLINGADDRESS1 {
        get {
        return ResourceManager.GetString("BILLINGADDRESS1", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Contact Nick Name.
        /// </summary>
        public static string CONTACTNICKNAME {
        get {
        return ResourceManager.GetString("CONTACTNICKNAME", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Contact Middle Name.
        /// </summary>
        public static string CONTACTMIDDLENAME {
        get {
        return ResourceManager.GetString("CONTACTMIDDLENAME", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Contact First Name.
        /// </summary>
        public static string CONTACTFIRSTNAME {
        get {
        return ResourceManager.GetString("CONTACTFIRSTNAME", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Contact Last Name.
        /// </summary>
        public static string CONTACTLASTNAME {
        get {
        return ResourceManager.GetString("CONTACTLASTNAME", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Legal Name.
        /// </summary>
        public static string LEGALNAME {
        get {
        return ResourceManager.GetString("LEGALNAME", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME {
        get {
        return ResourceManager.GetString("NAME", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Parent Relationship.
        /// </summary>
        public static string PARENTRELATIONSHIP {
        get {
        return ResourceManager.GetString("PARENTRELATIONSHIP", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Parent Internal ID.
        /// </summary>
        public static string PARENTINTERNALID {
        get {
        return ResourceManager.GetString("PARENTINTERNALID", resourceCulture);
        }
        }
      

        /// <summary>
        ///   Looks up a localized string similar to Internal ID.
        /// </summary>
        public static string INTERNALID {
        get {
        return ResourceManager.GetString("INTERNALID", resourceCulture);
        }
        }
      

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal DescriptionResource()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if ((resourceMan == null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOS.EasyBuyCycles.Shared.Properties.DescriptionResource", typeof(DescriptionResource).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}
		
		// A4DN Resources
	}
}